language: node_js
node_js:
  - "14.16"

jobs:
  include:
    - stage: npm release
      node_js: "14.16
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on:
          tags: true
